$primary_paletteKeyColor = 01b0c7
$secondary_paletteKeyColor = 2a8291
$tertiary_paletteKeyColor = 5a78ab
$neutral_paletteKeyColor = 737782
$neutral_variant_paletteKeyColor = 6e778a
$background = 0f131c
$onBackground = dfe2ef
$surface = 0f131c
$surfaceDim = 0f131c
$surfaceBright = 353943
$surfaceContainerLowest = 0a0e17
$surfaceContainerLow = 171c25
$surfaceContainer = 1b2029
$surfaceContainerHigh = 252a33
$surfaceContainerHighest = 30353e
$onSurface = dfe2ef
$surfaceVariant = 3e4759
$onSurfaceVariant = bec7dc
$inverseSurface = dfe2ef
$inverseOnSurface = 2c303a
$outline = 8891a5
$outlineVariant = 3e4759
$shadow = 000000
$scrim = 000000
$surfaceTint = 51d7ef
$primary = 51d7ef
$onPrimary = 00363e
$primaryContainer = 004e5a
$onPrimaryContainer = a1efff
$inversePrimary = 006876
$secondary = 83d3e3
$onSecondary = 00363e
$secondaryContainer = 026d7c
$onSecondaryContainer = a1efff
$tertiary = a9c7ff
$onTertiary = 09305f
$tertiaryContainer = 7391c6
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = a1efff
$primaryFixedDim = 51d7ef
$onPrimaryFixed = 001f25
$onPrimaryFixedVariant = 004e5a
$secondaryFixed = a1efff
$secondaryFixedDim = 83d3e3
$onSecondaryFixed = 001f25
$onSecondaryFixedVariant = 004e5a
$tertiaryFixed = d6e3ff
$tertiaryFixedDim = a9c7ff
$onTertiaryFixed = 001b3d
$onTertiaryFixedVariant = 274777
$term0 = 343434
$term1 = 8383ff
$term2 = 42e1da
$term3 = 75fcdd
$term4 = 77b4bf
$term5 = 7aaee9
$term6 = 80d7da
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 03f6ef
$term11 = c9fff3
$term12 = a4c7cb
$term13 = a2c0f7
$term14 = 87ebed
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = bae2ff
$mauve = 6fcbf7
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d0f9f3
$green = 8af0f3
$teal = 9fecf7
$sky = 95e8f8
$sapphire = 75d4ec
$blue = 62caeb
$lavender = 8dd7f5
$klink = 0094b0
$klinkSelection = 0094b1
$kvisited = 008aba
$kvisitedSelection = 008abb
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bcc2
$kpositiveSelection = 00bbc4
$text = dfe2ef
$subtext1 = bec7dc
$subtext0 = 8891a5
$overlay2 = 767e90
$overlay1 = 646b7b
$overlay0 = 535968
$surface2 = 424856
$surface1 = 323743
$surface0 = 20252f
$base = 0f131c
$mantle = 0f131c
$crust = 0e121b
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
